"use strict";
exports.__esModule = true;
var Teams_1 = require("./Teams");
exports.teamsArray = [];
var team1 = new Teams_1.Team("Galatasaray", 8);
var team2 = new Teams_1.Team("Beşiktaş", 7);
var team3 = new Teams_1.Team("AdanaDemirSpor", 3);
var team4 = new Teams_1.Team("Fenerbahçe", 7);
var team5 = new Teams_1.Team("Bursaspor", 5);
var team6 = new Teams_1.Team("Trabzonspor", 5);
var team7 = new Teams_1.Team("KSK", 5);
var team8 = new Teams_1.Team("Göztepe", 5);
var team9 = new Teams_1.Team("Altay", 2);
exports.teamsArray.push(team1);
exports.teamsArray.push(team2);
exports.teamsArray.push(team3);
exports.teamsArray.push(team4);
exports.teamsArray.push(team5);
exports.teamsArray.push(team6);
exports.teamsArray.push(team7);
exports.teamsArray.push(team8);
exports.teamsArray.push(team9);
